import './globals.css';
import {michromaFont, gtWalshFont } from '../app/fonts';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${gtWalshFont.variable} ${gtWalshFont.className} ${michromaFont.className} ${michromaFont.variable} `}>{children}</body>
      
    </html>
  )
}
